<?php
 return [
	'ads'=>[
		0=>[
		'status'=>'enabled',
		'network'=>'adsense',
		'name'=>'square',
		'code'=>'',
	],
		1=>[
		'status'=>'enabled',
		'network'=>'adsense',
		'name'=>'banner',
		'code'=>'',
	],
		2=>[
		'name'=>'below-search',
		'code'=>'',
		'network'=>'adsense',
		'status'=>'enabled',
	],
		3=>[
		'name'=>'above-steps',
		'code'=>'',
		'network'=>'adsense',
		'status'=>'enabled',
	],
		4=>[
		'name'=>'below-steps',
		'code'=>'',
		'network'=>'adsense',
		'status'=>'enabled',
	],
		5=>[
		'name'=>'above-how-to-download',
		'code'=>'',
		'network'=>'adsense',
		'status'=>'enabled',
	],
		6=>[
		'name'=>'below-how-to-download',
		'code'=>'',
		'network'=>'adsense',
		'status'=>'enabled',
	],
		7=>[
		'name'=>'above-faq',
		'code'=>'',
		'network'=>'adsense',
		'status'=>'enabled',
	],
	],
	'code'=>'',
];